name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: talesb/academy/.github/actions/maven_build@main

      - name: Build Docker Image
        run: docker build . --file  src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)


      - name: Verify Docker Images
        run: docker images
